### ISSUE TITLE
Cannot sign-in in local environment

### ISSUE THREAD

**Issue by mgurbanzade** [job-hax/backend#107]
Receiving `Invalid credentials` message on 
`https://backend.jobhax.com/api/users/auth_social_user` request in `data.error_message` response.

Steps I took to sign in

1. Created a superuser on local server
2. Generated google client id at https://developers.google.com/identity/sign-in/web/sign-in and assigned it to consecutive constant in [config.js](https://github.com/job-hax/frontend/blob/master/src/config/config.js)

3. Generated Recaptcha Site key and secret. Assigned the key to the constant in the same config file. Assigned the secret to the JOBHAX_RECAPTCHA_SECRET constant in `~/.bashrc`
4. Added an application following the instructions [here](https://github.com/job-hax/backend/blob/master/apidoc.md).
5. Assigned Jobhax client id and client secret to consecutive constants in config file.
6. On `localhost:8080/signin` tried to sign in via gmail and got that error.
7. Tried to sign in with superuser credentials and got the same error again.

What I'm doing wrong?

**Comment by hellsayenci** [comment]
Hey mgurbanzade,
Thank you for the detailed explanation for the issue. Can you pull the latest code and share inapp_error.log file after you get this error? 
Thank you!
